development: &default
  adapter: postgresql
  database: hacerspace_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: esref123++

test:
  <<: *default
  database: hacerspace_test

production:
  <<: *default
  database: hacerspace_production 

staging:
  <<: *default
  database: hacerspace_staging   